formatter: "markdown"

sections:
  show:
    - inputs
    - outputs
    - providers
    - requirements

content: |-
  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

settings:
  hide-empty: true